### ISSUE TITLE
Swiped notifications return

### ISSUE THREAD

**Issue by haarp** [MCMrARM/revolution-irc#76] opened 2018-01-01 12:31 UTC
When a notification for a query or channel message is swiped away, it'll return as soon as the app / server manager is opened. The only way to get rid of it for good is to visit the source (the tab) of the notification.

**Comment by MCMrARM** [comment] 2018-01-01 12:49
Can't reproduce. OS version?

**Comment by haarp** [comment] 2018-01-01 12:53
Android 6.0.1 (Cyanogenmod)

Reproduction:

- Be in random channel
- Receive notification from different channel/query
- Swipe notification away
- Press back

-> Enters server manager, notification returns

**Comment by MCMrARM** [comment] 2018-01-01 12:56
Can't reproduce.
Probably affects only Android version pre-7.0.

**Comment by target111** [comment] 2018-09-29 15:08
I thought this was the default behavior and therefore didn't have an issue with it.. one thing I have an issue with though is that if you get a notification about a message and that messages window is closed due to a network reconnect that notification will keep popping back even if swiped away or clicked.

**Comment by MCMrARM** [comment] 2019-01-21 21:33
This should be largely fixed now.

**Closed by MCMrARM** 2019-01-21 21:33 UTC
Labels: bug

**Comment by haarp** [comment] 2019-01-21 21:36
thanks a lot!
