### ISSUE TITLE
Long messages appear to be send, but go nowhere.

### ISSUE THREAD

**Issue by Mikaela** [MCMrARM/revolution-irc#102] opened 2018-02-16 17:50 UTC
1. Go to https://lipsum.com/feed/html and copy the first paragraph

```
 Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus id mauris ligula. Curabitur sem orci, convallis id fringilla id, mollis eu lorem. Nulla at justo a ligula ornare rutrum. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi vehicula dui nunc, nec mollis turpis egestas non. Pellentesque nunc enim, sollicitudin vitae est at, posuere vehicula ex. Vestibulum non ligula neque. Fusce rutrum magna lorem, id pharetra est efficitur sed. Praesent ut ultricies sem, nec convallis dui. 
```

2. Paste it to Revolution IRC and send it.
3. Look at the channel with another client.

Expected result: the message is sent and probably cut to smaller pieces as it's so long.

What happens instead: the message looks like it's sent, but no one else can see it.

**Comment by kurahaupo** [comment] 2018-02-20 01:38
Related issue #25 deals with over-long messages

**Comment by MCMrARM** [comment] 2018-02-20 12:11
Indeed, duplicate of #25.

**Closed by MCMrARM** 2018-02-20 12:11 UTC
Labels: bug
