### ISSUE TITLE
/msg yourself causes all future messages to appear in query with yourself

### ISSUE THREAD

**Issue by Mikaela** [MCMrARM/revolution-irc#36] opened 2017-11-10 16:26 UTC
1. /msg yournick hi
2. someone else messages you
3. you see the messages in query with yournick

I am not entirelyy sure if this is this issue or the method to reproduce it, but after doing this and reconnecting to ZNC, I see two queries with my nick and third with person I actually messaged to.

**Comment by MCMrARM** [comment] 2017-11-21 07:54
Duplicate of https://github.com/MCMrARM/revolution-irc/issues/26

**Closed by MCMrARM** 2017-11-21 07:54 UTC
Labels: bug, duplicate
