### ISSUE TITLE
Multiple notifications

### ISSUE THREAD

**Issue by clkircos** [MCMrARM/revolution-irc#17] opened 2017-10-27 17:55 UTC
I've been receiving multiple notifications for a single message on my Pixel 2 XL, eg:

https://imgur.com/lC8jmBT

**Comment by MCMrARM** [comment] 2017-10-27 18:49
This is... pretty bad and I can not reproduce it. Is this a bouncer (if so, what software)? Do the messages show up properly when you open the chat (there is a single one only)? Does it always happen? Does this happen immediately or you get a few notifications within a few second timespan?

**Comment by clkircos** [comment] 2017-10-27 21:35
No bouncer. Yep only one message when I open the chat. It seems to always happen and I think they all come through immediately but I'm not positive.

**Comment by MCMrARM** [comment] 2017-10-30 16:09
If you would like to help me debug the issue, you could join #revolutionirc on Freenode and I'll ask you to get a LogCat of a custom build to help me figure out the issue. I imagine this is a new bug with Android O.

**Comment by kuba-orlik** [comment] 2018-05-31 20:10
I'm ready to help debug this issue! It does affect me on my Android 7.1. I will get a LogCat of a custom build, if you'll send it my way :)

**Comment by 19lmyers** [comment] 2018-06-21 07:16
I think I'm also experiencing this issue.

**Comment by MCMrARM** [comment] 2018-06-21 15:31
I still can't reproduce, but the cause in the code has been and this will be fixed.

**Comment by MCMrARM** [comment] 2018-08-19 16:33
This has been fixed for 0.4.0 (earlier known as 0.3.3)

**Closed by MCMrARM** 2018-08-19 16:33 UTC
Labels: bug
