### ISSUE TITLE
Opening user list with gesture navigation

### ISSUE THREAD

**Issue by GreatGallopingSnail** [MCMrARM/revolution-irc#302] opened 2021-06-22 06:06 UTC
I'm using a Pixel 4a with gesture navigation. I'm unable to access the user list in a channel by swiping in from the left as Android recognizes that as the back command. Could the user list be added to the kebab menu in the upper right corner, or could there be another way of accessing it?

Please let me know if more information is needed, or if there's anything I can do to help.

**Comment by kurahaupo** [comment] 2021-07-05 23:58
Duplicate of #276

**Closed** 2022-01-30 22:42 UTC
