### ISSUE TITLE
Regular nicks unreadable in light theme

### ISSUE THREAD

**Issue by 14mRh4X0r** [MCMrARM/revolution-irc#200] opened 2019-03-02 10:24 UTC
In the light theme, regular nicks in the nick list are white against a very light grey background, and thus unreadable.

Phone: Xiaomi Mi A2 Lite, Android 9 (Android One)

**Comment by MCMrARM** [comment] 2019-03-02 12:55
Duplicate of https://github.com/MCMrARM/revolution-irc/issues/199

**Closed by MCMrARM** 2019-03-02 12:55 UTC

**Comment by 14mRh4X0r** [comment] 2019-03-02 12:57
Oops, sorry
