### ISSUE TITLE
Auto-accept file download. Disable download dialog box. /sreq auto. Please help

### ISSUE THREAD

**Issue by Yehshua** [MCMrARM/revolution-irc#283] opened 2021-02-04 20:17 UTC
How do we turn on and make revolution irc app auto-accept file downloads so we don't have to click the accept button all the time? 

Is the option to auto-accept file downloads available somewhere in the app? /sreq auto don't work. Help appreciated.

**Comment by MCMrARM** [comment] 2021-02-05 13:37
Auto accepting file downloads is dangerous as hell, unless someone comes up with a way to do it semi-securely this is not going to happen.

Duplicate of https://github.com/MCMrARM/revolution-irc/issues/258

**Closed by MCMrARM** 2021-02-05 13:37 UTC

**Comment by Yehshua** [comment] 2021-02-06 06:16
> Auto accepting file downloads is dangerous as hell, unless someone comes up with a way to do it semi-securely this is not going to happen.
> 
> Duplicate of #258

Is there anyway we can get the downloads to auto-accept or any other way where we don't have to click on accept??

**Comment by kurahaupo** [comment] 2021-02-07 08:12
Perhaps this could be switchable on a per-server basis, since one could - in theory - have a private IRC server that one controls and is secure (enough) to allow this.

Since we're talking about an app running on a phone, it should only apply to servers that are accessed via a VPN over UMTS, or in the same broadcast domain on a WiFi LAN.

None of that would be trivial to implement.
