### ISSUE TITLE
When kicked, show the kick message in the channel kicked from

### ISSUE THREAD

**Issue by ZeroKnight** [MCMrARM/revolution-irc#108] opened 2018-02-20 01:05 UTC
As @kurahaupo mentioned in #100:
> When a user is kicked from a channel, it would be helpful to display that in the channel rather than in the server tab.

**Comment by kurahaupo** [comment] 2018-03-06 08:27
Probably a duplicate of #65

**Comment by MCMrARM** [comment] 2018-03-06 14:56
Not really, it's not a duplicate.

**Comment by MCMrARM** [comment] 2018-08-02 18:08
Support for this has been merged: https://github.com/MCMrARM/revolution-irc/pull/136

**Closed by MCMrARM** 2018-08-02 18:08 UTC
Labels: enhancement
