### ISSUE TITLE
Default white theme shouldn't have white text for users

### ISSUE THREAD

**Issue by tya99** [MCMrARM/revolution-irc#202] opened 2019-03-08 09:42 UTC
The default colored white theme shouldn't have white text as it's unreadable.

![screenshot_20190308-195715_revolution_irc](https://user-images.githubusercontent.com/42108382/54020694-47f25e00-4186-11e9-9853-e7f11fffa52a.png)

**Comment by MCMrARM** [comment] 2019-03-08 09:48
Duplicate of https://github.com/MCMrARM/revolution-irc/issues/199

**Closed by MCMrARM** 2019-03-08 09:48 UTC

**Comment by tya99** [comment] 2019-03-08 09:49
oops, sorry for not seeing that!
