### ISSUE TITLE
inputbox becomes weird after pasting text from clipboard

### ISSUE THREAD

**Issue by LaineZ** [MCMrARM/revolution-irc#236] opened 2020-01-03 18:32 UTC
inputbox is going crazy after pasting text from clipboard (input-lag, autocomplete clears word completely and after undetermined time app crashes...
it is possible that this is not client bug
Android 7.0, Revolution IRC 0.5.2, Keyboard: Gboard 5.1.18

**Comment by MCMrARM** [comment] 2020-01-08 11:33
Duplicate of https://github.com/MCMrARM/revolution-irc/issues/141

**Closed by MCMrARM** 2020-01-08 11:33 UTC
Labels: bug, duplicate
