### ISSUE TITLE
Member list text color

### ISSUE THREAD

**Issue by nfearnley** [MCMrARM/revolution-irc#207] opened 2019-03-21 16:10 UTC
I am using a theme with a black background. Occasionally, when I pull out the member list, all the nicknames will have a text color of black. This is fixed by opening up the theme settings, the resaving the theme. Once this is done, the text color appears properly for a while. Eventually, the text color reverts to black again.

**Comment by MCMrARM** [comment] 2019-03-21 18:54
Duplicate of https://github.com/MCMrARM/revolution-irc/issues/202

**Closed by MCMrARM** 2019-03-21 18:54 UTC
Labels: bug, duplicate
